### ISSUE TITLE
Not able to DL Foldarap2.5_yextruspoolandtherest.stl

### ISSUE THREAD

**Issue by Prometheus3DP** [EmmanuelG/Foldarap#3]
I have been trying to download this STL file but I just get a screen of parameters.
![foldaraperror](https://cloud.githubusercontent.com/assets/11560865/6743121/63db3592-ce6c-11e4-8a88-0afe75ec75fd.jpg)

**Comment by EmmanuelG** [comment]
Oh it happen sometimes depending of your system/browser/files, on the **raw** button right-click and choose to *save the target of the link as...* it should allow you to download this single file (or maybe try to download the complete folder as a zip ?
